// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMemory(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddMemory'](arg1, arg2, arg3);
}

export function AddToolSafeRule(arg1, arg2) {
  return window['go']['app']['App']['AddToolSafeRule'](arg1, arg2);
}

export function ApplySafetyPreset(arg1) {
  return window['go']['app']['App']['ApplySafetyPreset'](arg1);
}

export function BenchmarkProfile(arg1, arg2) {
  return window['go']['app']['App']['BenchmarkProfile'](arg1, arg2);
}

export function ClearBenchmarkRuns() {
  return window['go']['app']['App']['ClearBenchmarkRuns']();
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function ClearMemoryEntries() {
  return window['go']['app']['App']['ClearMemoryEntries']();
}

export function ClearSessionRecall() {
  return window['go']['app']['App']['ClearSessionRecall']();
}

export function ClearTaskRuns() {
  return window['go']['app']['App']['ClearTaskRuns']();
}

export function ClearTodos() {
  return window['go']['app']['App']['ClearTodos']();
}

export function CreateDir(arg1) {
  return window['go']['app']['App']['CreateDir'](arg1);
}

export function CreateFile(arg1) {
  return window['go']['app']['App']['CreateFile'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['app']['App']['DeleteFile'](arg1);
}

export function DeleteMemoryEntry(arg1) {
  return window['go']['app']['App']['DeleteMemoryEntry'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['app']['App']['DeleteSession'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['app']['App']['DeleteSkill'](arg1);
}

export function EncodeFileBase64(arg1) {
  return window['go']['app']['App']['EncodeFileBase64'](arg1);
}

export function GetAgentMode() {
  return window['go']['app']['App']['GetAgentMode']();
}

export function GetAutoAgents() {
  return window['go']['app']['App']['GetAutoAgents']();
}

export function GetAutonomous() {
  return window['go']['app']['App']['GetAutonomous']();
}

export function GetFileTree(arg1) {
  return window['go']['app']['App']['GetFileTree'](arg1);
}

export function GetHistoryStats() {
  return window['go']['app']['App']['GetHistoryStats']();
}

export function GetHomeDir() {
  return window['go']['app']['App']['GetHomeDir']();
}

export function GetProfileNames() {
  return window['go']['app']['App']['GetProfileNames']();
}

export function GetProfiles() {
  return window['go']['app']['App']['GetProfiles']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetSkill(arg1) {
  return window['go']['app']['App']['GetSkill'](arg1);
}

export function GetUserProfile() {
  return window['go']['app']['App']['GetUserProfile']();
}

export function GetWorkingDir() {
  return window['go']['app']['App']['GetWorkingDir']();
}

export function ListBenchmarkRuns() {
  return window['go']['app']['App']['ListBenchmarkRuns']();
}

export function ListMemory() {
  return window['go']['app']['App']['ListMemory']();
}

export function ListModels() {
  return window['go']['app']['App']['ListModels']();
}

export function ListModelsForProvider(arg1) {
  return window['go']['app']['App']['ListModelsForProvider'](arg1);
}

export function ListSessions() {
  return window['go']['app']['App']['ListSessions']();
}

export function ListSkills() {
  return window['go']['app']['App']['ListSkills']();
}

export function ListTaskRuns() {
  return window['go']['app']['App']['ListTaskRuns']();
}

export function ListTodos() {
  return window['go']['app']['App']['ListTodos']();
}

export function LoadSession(arg1) {
  return window['go']['app']['App']['LoadSession'](arg1);
}

export function OpenShell() {
  return window['go']['app']['App']['OpenShell']();
}

export function PickSaveFilePath(arg1) {
  return window['go']['app']['App']['PickSaveFilePath'](arg1);
}

export function Ping() {
  return window['go']['app']['App']['Ping']();
}

export function PingProvider(arg1) {
  return window['go']['app']['App']['PingProvider'](arg1);
}

export function ReadFileContent(arg1) {
  return window['go']['app']['App']['ReadFileContent'](arg1);
}

export function ReindexSessionRecall() {
  return window['go']['app']['App']['ReindexSessionRecall']();
}

export function RenameFile(arg1, arg2) {
  return window['go']['app']['App']['RenameFile'](arg1, arg2);
}

export function RespondConfirm(arg1) {
  return window['go']['app']['App']['RespondConfirm'](arg1);
}

export function RollbackDepth() {
  return window['go']['app']['App']['RollbackDepth']();
}

export function RunArtifact(arg1, arg2) {
  return window['go']['app']['App']['RunArtifact'](arg1, arg2);
}

export function RunDoctor() {
  return window['go']['app']['App']['RunDoctor']();
}

export function SaveFileContent(arg1, arg2) {
  return window['go']['app']['App']['SaveFileContent'](arg1, arg2);
}

export function SaveMemoryEntry(arg1) {
  return window['go']['app']['App']['SaveMemoryEntry'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['app']['App']['SaveSession'](arg1);
}

export function SaveSkill(arg1) {
  return window['go']['app']['App']['SaveSkill'](arg1);
}

export function SaveUserProfile(arg1) {
  return window['go']['app']['App']['SaveUserProfile'](arg1);
}

export function SearchSessionRecall(arg1, arg2) {
  return window['go']['app']['App']['SearchSessionRecall'](arg1, arg2);
}

export function SelectWorkingDir(arg1) {
  return window['go']['app']['App']['SelectWorkingDir'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SetAgentModeOverride(arg1) {
  return window['go']['app']['App']['SetAgentModeOverride'](arg1);
}

export function SetAutoAgents(arg1) {
  return window['go']['app']['App']['SetAutoAgents'](arg1);
}

export function SetAutonomous(arg1) {
  return window['go']['app']['App']['SetAutonomous'](arg1);
}

export function SetWorkingDir(arg1) {
  return window['go']['app']['App']['SetWorkingDir'](arg1);
}

export function ShellClose(arg1) {
  return window['go']['app']['App']['ShellClose'](arg1);
}

export function ShellInput(arg1, arg2) {
  return window['go']['app']['App']['ShellInput'](arg1, arg2);
}

export function StopAgent() {
  return window['go']['app']['App']['StopAgent']();
}

export function StopArtifact() {
  return window['go']['app']['App']['StopArtifact']();
}

export function SwitchProfile(arg1) {
  return window['go']['app']['App']['SwitchProfile'](arg1);
}

export function Undo() {
  return window['go']['app']['App']['Undo']();
}

export function UpdateProfiles(arg1) {
  return window['go']['app']['App']['UpdateProfiles'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function UseProfile(arg1, arg2, arg3) {
  return window['go']['app']['App']['UseProfile'](arg1, arg2, arg3);
}
