// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engagement} from '../models';
import {app} from '../models';
import {settings} from '../models';
import {packlibrary} from '../models';
import {channelbus} from '../models';
import {ledger} from '../models';
import {llm} from '../models';
import {tools} from '../models';
import {sessionstore} from '../models';

export function AddEngagementEndpoint(arg1:string,arg2:engagement.EndpointInput):Promise<engagement.Endpoint>;

export function AddEngagementEvidence(arg1:string,arg2:engagement.EvidenceInput):Promise<engagement.Evidence>;

export function AddMemory(arg1:string,arg2:string,arg3:Array<string>):Promise<app.MemoryEntry>;

export function AddToolSafeRule(arg1:string,arg2:string):Promise<void>;

export function AddWorkspaceFolder(arg1:string,arg2:string):Promise<Array<settings.WorkspaceFolder>>;

export function ApplySafetyPreset(arg1:string):Promise<void>;

export function BenchmarkProfile(arg1:settings.Profile,arg2:settings.Provider):Promise<app.ProfileBenchmarkResult>;

export function BenchmarkProfileWithCases(arg1:settings.Profile,arg2:settings.Provider,arg3:Array<app.BenchmarkSpecInput>):Promise<app.ProfileBenchmarkResult>;

export function CalibrateSpec(arg1:string):Promise<app.SpecCalibration>;

export function CheckEngagementTarget():Promise<app.EngagementTargetProbe>;

export function ClearAgentEvalReports():Promise<void>;

export function ClearBenchmarkRuns():Promise<void>;

export function ClearHistory():Promise<void>;

export function ClearLedgerEvents():Promise<void>;

export function ClearMemoryEntries():Promise<void>;

export function ClearProviderAPIKey(arg1:string):Promise<void>;

export function ClearSessionRecall():Promise<void>;

export function ClearStorageItem(arg1:string):Promise<void>;

export function ClearTaskRuns():Promise<void>;

export function ClearTodos():Promise<void>;

export function ClonePack(arg1:packlibrary.CloneInput):Promise<packlibrary.Summary>;

export function ConfirmEngagementFinding(arg1:string,arg2:string,arg3:number,arg4:string):Promise<engagement.Finding>;

export function CreateDir(arg1:string):Promise<void>;

export function CreateEngagement(arg1:string,arg2:string,arg3:Array<string>):Promise<engagement.Record>;

export function CreateFile(arg1:string):Promise<void>;

export function DeleteEngagement(arg1:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function DeleteMemoryEntry(arg1:string):Promise<void>;

export function DeleteSession(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function DeleteTelegramMessage(arg1:string,arg2:string):Promise<void>;

export function DispatchChannelMessage(arg1:channelbus.Envelope):Promise<channelbus.Response>;

export function DispatchSideChatMessage(arg1:channelbus.Envelope):Promise<channelbus.Response>;

export function EmergencyStop():Promise<Record<string, number>>;

export function EncodeFileBase64(arg1:string):Promise<string>;

export function ExportEngagementJSON(arg1:string):Promise<string>;

export function ExportMemoryJSON():Promise<string>;

export function ExportPackJSON(arg1:string):Promise<string>;

export function ExportTaskRunsJSON():Promise<string>;

export function GetAgentMode():Promise<string>;

export function GetAudioHealth():Promise<app.AudioHealth>;

export function GetAutoAgents():Promise<boolean>;

export function GetAutonomous():Promise<boolean>;

export function GetChannelBusStatus():Promise<Record<string, string>>;

export function GetEngagement(arg1:string):Promise<engagement.Record>;

export function GetEngagementAvailable(arg1:string,arg2:number):Promise<engagement.AvailableWork>;

export function GetEngagementNext(arg1:string):Promise<engagement.NextAction>;

export function GetEngagementSetupPreview():Promise<app.EngagementSetupPreview>;

export function GetFileTree(arg1:string):Promise<Array<app.FileNode>>;

export function GetHistoryStats():Promise<app.HistoryStats>;

export function GetHomeDir():Promise<string>;

export function GetLabStatus():Promise<app.LabStatus>;

export function GetNextContextPacketClass():Promise<string>;

export function GetProfileNames():Promise<Array<string>>;

export function GetProfiles():Promise<settings.ProfilesFile>;

export function GetProjectInstructionsSummary():Promise<string>;

export function GetProviderAPIKeyStatus(arg1:settings.Provider):Promise<settings.ProviderAPIKeyStatus>;

export function GetServiceHealth():Promise<Array<app.ServiceHealth>>;

export function GetSettings():Promise<settings.Settings>;

export function GetSharedTerminalState():Promise<app.TerminalStateSnapshot>;

export function GetSkill(arg1:string):Promise<app.Skill>;

export function GetSpecCalibration():Promise<app.SpecCalibration>;

export function GetSpecPlan():Promise<app.SpecPlan>;

export function GetUserProfile():Promise<string>;

export function GetWorkingDir():Promise<string>;

export function ImportEngagementJSON(arg1:string):Promise<engagement.Record>;

export function ImportMemoryJSON(arg1:string):Promise<number>;

export function ImportPackJSON(arg1:string,arg2:string):Promise<packlibrary.Summary>;

export function ImportTaskRunsJSON(arg1:string):Promise<number>;

export function IngestVideo(arg1:string,arg2:string):Promise<app.VideoIngest>;

export function IngestVideoPath(arg1:string):Promise<app.VideoIngest>;

export function InterruptShellTool():Promise<void>;

export function KillLocalInferenceServers():Promise<app.MaintenanceResult>;

export function ListAgentDefinitions():Promise<Array<app.AgentDefinition>>;

export function ListAgentSessions():Promise<Array<app.AgentSession>>;

export function ListBenchmarkRuns():Promise<Array<app.ProfileBenchmarkResult>>;

export function ListChannelWorkQueue():Promise<Array<channelbus.WorkItem>>;

export function ListEngagements():Promise<Array<engagement.Summary>>;

export function ListKokoroVoices():Promise<Array<string>>;

export function ListLearningCandidates(arg1:number):Promise<Array<app.LearningCandidate>>;

export function ListLedgerEvents(arg1:number):Promise<Array<ledger.Event>>;

export function ListMemory():Promise<Array<app.MemoryEntry>>;

export function ListModelMetadataForProvider(arg1:settings.Provider):Promise<Array<llm.ModelMetadata>>;

export function ListModels():Promise<Array<string>>;

export function ListModelsForProvider(arg1:settings.Provider):Promise<Array<string>>;

export function ListPackLibrary():Promise<packlibrary.Snapshot>;

export function ListResumableRuns():Promise<Array<app.RunCheckpoint>>;

export function ListSessions():Promise<Array<string>>;

export function ListSkills():Promise<Array<app.Skill>>;

export function ListStorageItems():Promise<Array<app.StorageItem>>;

export function ListTaskRuns():Promise<Array<app.TaskRun>>;

export function ListTodos():Promise<Array<tools.TodoItem>>;

export function ListVPNInterfaces():Promise<Array<app.VPNInterfaceInfo>>;

export function ListWSLDistros():Promise<Array<string>>;

export function ListWorkspaceFolders():Promise<Array<settings.WorkspaceFolder>>;

export function LoadBenchmarkModel(arg1:settings.Profile,arg2:settings.Provider):Promise<app.ProfileBenchmarkResult>;

export function LoadSession(arg1:string):Promise<Array<app.SessionChatMessage>>;

export function OpenShell():Promise<string>;

export function PickSaveFilePath(arg1:string):Promise<string>;

export function Ping():Promise<string>;

export function PingProvider(arg1:settings.Provider):Promise<string>;

export function PreviewContext(arg1:string,arg2:string):Promise<app.ContextInspection>;

export function PruneLedgerEvents(arg1:string,arg2:Array<string>):Promise<number>;

export function ReadFileContent(arg1:string):Promise<string>;

export function RecommendModelProfileTemplate(arg1:settings.Profile):Promise<app.ModelProfileTemplateResult>;

export function RecordLearningDecision(arg1:app.LearningCandidate,arg2:string,arg3:string):Promise<void>;

export function RecoverSharedTerminal():Promise<app.TerminalRecoveryResult>;

export function ReindexSessionRecall():Promise<number>;

export function ReleaseEngagementClaim(arg1:string,arg2:string):Promise<engagement.WorkState>;

export function RemoveWorkspaceFolder(arg1:string):Promise<Array<settings.WorkspaceFolder>>;

export function RenameFile(arg1:string,arg2:string):Promise<void>;

export function RespondConfirm(arg1:boolean):Promise<void>;

export function RestartAudioWorker():Promise<app.AudioHealth>;

export function RestartWSL():Promise<app.MaintenanceResult>;

export function ResumeRun(arg1:string):Promise<void>;

export function RollbackDepth():Promise<number>;

export function RunAgentEval(arg1:string):Promise<app.AgentEvalReport>;

export function RunAgentEvalRepeated(arg1:string,arg2:number):Promise<app.AgentEvalReport>;

export function RunArtifact(arg1:string,arg2:string):Promise<void>;

export function RunContextQualityEval(arg1:string,arg2:number):Promise<app.ContextQualityReport>;

export function RunDoctor():Promise<app.DoctorResult>;

export function RunEngagementAgentEval():Promise<app.AgentEvalReport>;

export function RunGrammarToolArgsProbe(arg1:string):Promise<app.GrammarToolArgsProbeResult>;

export function RunJHUTAgentEval(arg1:string):Promise<app.AgentEvalReport>;

export function RunJHUTBrowserVerification(arg1:string):Promise<app.JHUTBrowserReport>;

export function RunMiniAgentLoopBenchmark(arg1:settings.Profile,arg2:settings.Provider):Promise<app.AgentEvalResult>;

export function SaveFileContent(arg1:string,arg2:string):Promise<void>;

export function SaveMemoryEntry(arg1:app.MemoryEntry):Promise<app.MemoryEntry>;

export function SaveSession(arg1:string):Promise<void>;

export function SaveSkill(arg1:app.Skill):Promise<app.Skill>;

export function SaveUserProfile(arg1:string):Promise<void>;

export function ScaffoldWorkspaceFolders(arg1:string,arg2:Array<string>):Promise<Array<string>>;

export function SearchSessionRecall(arg1:string,arg2:number):Promise<Array<sessionstore.SearchResult>>;

export function SelectProjectInstructionDirectory(arg1:string):Promise<string>;

export function SelectProjectInstructionFile(arg1:string):Promise<string>;

export function SelectWorkingDir(arg1:string):Promise<string>;

export function SelectWorkspaceFolder(arg1:string):Promise<string>;

export function SendMessage(arg1:string,arg2:Array<string>,arg3:Array<app.ChatAttachment>):Promise<void>;

export function SendMessageWithProfile(arg1:string,arg2:Array<string>,arg3:Array<app.ChatAttachment>,arg4:string):Promise<void>;

export function SendTelegramMessage(arg1:string,arg2:string):Promise<string>;

export function SetAgentModeOverride(arg1:string):Promise<void>;

export function SetAutoAgents(arg1:boolean):Promise<void>;

export function SetAutonomous(arg1:boolean):Promise<void>;

export function SetEngagementEndpointGroup(arg1:string,arg2:string,arg3:string):Promise<engagement.Endpoint>;

export function SetEngagementNotes(arg1:string,arg2:string,arg3:number):Promise<number>;

export function SetNextContextPacketClass(arg1:string):Promise<string>;

export function SetPackArchived(arg1:string,arg2:boolean):Promise<packlibrary.Summary>;

export function SetProviderAPIKey(arg1:string,arg2:string):Promise<void>;

export function SetSpecMode(arg1:string):Promise<app.SpecPlan>;

export function SetWorkingDir(arg1:string):Promise<void>;

export function ShellClose(arg1:string):Promise<void>;

export function ShellInput(arg1:string,arg2:string):Promise<void>;

export function ShellResize(arg1:string,arg2:number,arg3:number):Promise<void>;

export function StopAgent():Promise<void>;

export function StopArtifact():Promise<void>;

export function SwitchProfile(arg1:string):Promise<void>;

export function SynthesizeSpeech(arg1:string):Promise<app.SpeechAudio>;

export function TranscribeVoiceClip(arg1:string):Promise<string>;

export function Undo():Promise<string>;

export function UpdateLabContext(arg1:string,arg2:string,arg3:string,arg4:string):Promise<app.LabStatus>;

export function UpdateProfiles(arg1:settings.ProfilesFile):Promise<void>;

export function UpdateSettings(arg1:settings.Settings):Promise<void>;

export function UpsertEngagementFinding(arg1:string,arg2:engagement.FindingInput):Promise<engagement.Finding>;

export function UseProfile(arg1:string,arg2:settings.Settings,arg3:settings.ProfilesFile):Promise<void>;

export function UseProjectInstructionFile(arg1:string):Promise<settings.Settings>;
