// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddEngagementEndpoint(arg1, arg2) {
  return window['go']['app']['App']['AddEngagementEndpoint'](arg1, arg2);
}

export function AddEngagementEvidence(arg1, arg2) {
  return window['go']['app']['App']['AddEngagementEvidence'](arg1, arg2);
}

export function AddMemory(arg1, arg2, arg3) {
  return window['go']['app']['App']['AddMemory'](arg1, arg2, arg3);
}

export function AddToolSafeRule(arg1, arg2) {
  return window['go']['app']['App']['AddToolSafeRule'](arg1, arg2);
}

export function AddWorkspaceFolder(arg1, arg2) {
  return window['go']['app']['App']['AddWorkspaceFolder'](arg1, arg2);
}

export function ApplySafetyPreset(arg1) {
  return window['go']['app']['App']['ApplySafetyPreset'](arg1);
}

export function BenchmarkProfile(arg1, arg2) {
  return window['go']['app']['App']['BenchmarkProfile'](arg1, arg2);
}

export function BenchmarkProfileWithCases(arg1, arg2, arg3) {
  return window['go']['app']['App']['BenchmarkProfileWithCases'](arg1, arg2, arg3);
}

export function CalibrateSpec(arg1) {
  return window['go']['app']['App']['CalibrateSpec'](arg1);
}

export function CancelRepositorySplitReview() {
  return window['go']['app']['App']['CancelRepositorySplitReview']();
}

export function CancelWorkspaceRepositoryIndex() {
  return window['go']['app']['App']['CancelWorkspaceRepositoryIndex']();
}

export function CheckEngagementTarget() {
  return window['go']['app']['App']['CheckEngagementTarget']();
}

export function ClearAgentEvalReports() {
  return window['go']['app']['App']['ClearAgentEvalReports']();
}

export function ClearBenchmarkRuns() {
  return window['go']['app']['App']['ClearBenchmarkRuns']();
}

export function ClearHistory() {
  return window['go']['app']['App']['ClearHistory']();
}

export function ClearLedgerEvents() {
  return window['go']['app']['App']['ClearLedgerEvents']();
}

export function ClearMemoryEntries() {
  return window['go']['app']['App']['ClearMemoryEntries']();
}

export function ClearProviderAPIKey(arg1) {
  return window['go']['app']['App']['ClearProviderAPIKey'](arg1);
}

export function ClearSessionRecall() {
  return window['go']['app']['App']['ClearSessionRecall']();
}

export function ClearStorageItem(arg1) {
  return window['go']['app']['App']['ClearStorageItem'](arg1);
}

export function ClearTaskRuns() {
  return window['go']['app']['App']['ClearTaskRuns']();
}

export function ClearTodos() {
  return window['go']['app']['App']['ClearTodos']();
}

export function ClonePack(arg1) {
  return window['go']['app']['App']['ClonePack'](arg1);
}

export function ConfirmEngagementFinding(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['ConfirmEngagementFinding'](arg1, arg2, arg3, arg4);
}

export function CreateDir(arg1) {
  return window['go']['app']['App']['CreateDir'](arg1);
}

export function CreateEngagement(arg1, arg2, arg3) {
  return window['go']['app']['App']['CreateEngagement'](arg1, arg2, arg3);
}

export function CreateFile(arg1) {
  return window['go']['app']['App']['CreateFile'](arg1);
}

export function CreateScratchWorkspace(arg1) {
  return window['go']['app']['App']['CreateScratchWorkspace'](arg1);
}

export function CreateWorkspaceProject(arg1, arg2) {
  return window['go']['app']['App']['CreateWorkspaceProject'](arg1, arg2);
}

export function DeleteEngagement(arg1) {
  return window['go']['app']['App']['DeleteEngagement'](arg1);
}

export function DeleteFile(arg1) {
  return window['go']['app']['App']['DeleteFile'](arg1);
}

export function DeleteMemoryEntry(arg1) {
  return window['go']['app']['App']['DeleteMemoryEntry'](arg1);
}

export function DeleteResumableRun(arg1) {
  return window['go']['app']['App']['DeleteResumableRun'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['app']['App']['DeleteSession'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['app']['App']['DeleteSkill'](arg1);
}

export function DeleteTelegramMessage(arg1, arg2) {
  return window['go']['app']['App']['DeleteTelegramMessage'](arg1, arg2);
}

export function DispatchChannelMessage(arg1) {
  return window['go']['app']['App']['DispatchChannelMessage'](arg1);
}

export function DispatchSideChatMessage(arg1) {
  return window['go']['app']['App']['DispatchSideChatMessage'](arg1);
}

export function EmergencyStop() {
  return window['go']['app']['App']['EmergencyStop']();
}

export function EncodeFileBase64(arg1) {
  return window['go']['app']['App']['EncodeFileBase64'](arg1);
}

export function ExportEngagementJSON(arg1) {
  return window['go']['app']['App']['ExportEngagementJSON'](arg1);
}

export function ExportMemoryJSON() {
  return window['go']['app']['App']['ExportMemoryJSON']();
}

export function ExportPackJSON(arg1) {
  return window['go']['app']['App']['ExportPackJSON'](arg1);
}

export function ExportTaskRunsJSON() {
  return window['go']['app']['App']['ExportTaskRunsJSON']();
}

export function GetAgentMode() {
  return window['go']['app']['App']['GetAgentMode']();
}

export function GetAudioHealth() {
  return window['go']['app']['App']['GetAudioHealth']();
}

export function GetAutoAgents() {
  return window['go']['app']['App']['GetAutoAgents']();
}

export function GetAutonomous() {
  return window['go']['app']['App']['GetAutonomous']();
}

export function GetBrowserWorkflowStatus() {
  return window['go']['app']['App']['GetBrowserWorkflowStatus']();
}

export function GetChannelBusStatus() {
  return window['go']['app']['App']['GetChannelBusStatus']();
}

export function GetConversationMode() {
  return window['go']['app']['App']['GetConversationMode']();
}

export function GetEngagement(arg1) {
  return window['go']['app']['App']['GetEngagement'](arg1);
}

export function GetEngagementAvailable(arg1, arg2) {
  return window['go']['app']['App']['GetEngagementAvailable'](arg1, arg2);
}

export function GetEngagementNext(arg1) {
  return window['go']['app']['App']['GetEngagementNext'](arg1);
}

export function GetEngagementSetupPreview() {
  return window['go']['app']['App']['GetEngagementSetupPreview']();
}

export function GetFileTree(arg1) {
  return window['go']['app']['App']['GetFileTree'](arg1);
}

export function GetHistoryStats() {
  return window['go']['app']['App']['GetHistoryStats']();
}

export function GetHomeDir() {
  return window['go']['app']['App']['GetHomeDir']();
}

export function GetLabStatus() {
  return window['go']['app']['App']['GetLabStatus']();
}

export function GetNextContextPacketClass() {
  return window['go']['app']['App']['GetNextContextPacketClass']();
}

export function GetProfileNames() {
  return window['go']['app']['App']['GetProfileNames']();
}

export function GetProfiles() {
  return window['go']['app']['App']['GetProfiles']();
}

export function GetProjectInstructionsSummary() {
  return window['go']['app']['App']['GetProjectInstructionsSummary']();
}

export function GetProviderAPIKeyStatus(arg1) {
  return window['go']['app']['App']['GetProviderAPIKeyStatus'](arg1);
}

export function GetRepositoryIndexSources() {
  return window['go']['app']['App']['GetRepositoryIndexSources']();
}

export function GetRepositoryIndexStatus() {
  return window['go']['app']['App']['GetRepositoryIndexStatus']();
}

export function GetRepositoryReviewStatus() {
  return window['go']['app']['App']['GetRepositoryReviewStatus']();
}

export function GetRunEventDiagnostics() {
  return window['go']['app']['App']['GetRunEventDiagnostics']();
}

export function GetScratchWorkspaceStatus() {
  return window['go']['app']['App']['GetScratchWorkspaceStatus']();
}

export function GetServiceHealth() {
  return window['go']['app']['App']['GetServiceHealth']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetSharedTerminalState() {
  return window['go']['app']['App']['GetSharedTerminalState']();
}

export function GetSkill(arg1) {
  return window['go']['app']['App']['GetSkill'](arg1);
}

export function GetSpecCalibration() {
  return window['go']['app']['App']['GetSpecCalibration']();
}

export function GetSpecPlan() {
  return window['go']['app']['App']['GetSpecPlan']();
}

export function GetUserProfile() {
  return window['go']['app']['App']['GetUserProfile']();
}

export function GetWorkingDir() {
  return window['go']['app']['App']['GetWorkingDir']();
}

export function ImportEngagementJSON(arg1) {
  return window['go']['app']['App']['ImportEngagementJSON'](arg1);
}

export function ImportMemoryJSON(arg1) {
  return window['go']['app']['App']['ImportMemoryJSON'](arg1);
}

export function ImportPackJSON(arg1, arg2) {
  return window['go']['app']['App']['ImportPackJSON'](arg1, arg2);
}

export function ImportTaskRunsJSON(arg1) {
  return window['go']['app']['App']['ImportTaskRunsJSON'](arg1);
}

export function IndexWorkspaceRepository() {
  return window['go']['app']['App']['IndexWorkspaceRepository']();
}

export function IngestVideo(arg1, arg2) {
  return window['go']['app']['App']['IngestVideo'](arg1, arg2);
}

export function IngestVideoPath(arg1) {
  return window['go']['app']['App']['IngestVideoPath'](arg1);
}

export function InspectSessionRepair(arg1) {
  return window['go']['app']['App']['InspectSessionRepair'](arg1);
}

export function InterruptShellTool() {
  return window['go']['app']['App']['InterruptShellTool']();
}

export function KillLocalInferenceServers() {
  return window['go']['app']['App']['KillLocalInferenceServers']();
}

export function ListAgentDefinitions() {
  return window['go']['app']['App']['ListAgentDefinitions']();
}

export function ListAgentSessions() {
  return window['go']['app']['App']['ListAgentSessions']();
}

export function ListBenchmarkRuns() {
  return window['go']['app']['App']['ListBenchmarkRuns']();
}

export function ListBrowserCheckpoints() {
  return window['go']['app']['App']['ListBrowserCheckpoints']();
}

export function ListChannelWorkQueue() {
  return window['go']['app']['App']['ListChannelWorkQueue']();
}

export function ListEngagements() {
  return window['go']['app']['App']['ListEngagements']();
}

export function ListKokoroVoices() {
  return window['go']['app']['App']['ListKokoroVoices']();
}

export function ListLearningCandidates(arg1) {
  return window['go']['app']['App']['ListLearningCandidates'](arg1);
}

export function ListLedgerEvents(arg1) {
  return window['go']['app']['App']['ListLedgerEvents'](arg1);
}

export function ListMemory() {
  return window['go']['app']['App']['ListMemory']();
}

export function ListModelMetadataForProvider(arg1) {
  return window['go']['app']['App']['ListModelMetadataForProvider'](arg1);
}

export function ListModels() {
  return window['go']['app']['App']['ListModels']();
}

export function ListModelsForProvider(arg1) {
  return window['go']['app']['App']['ListModelsForProvider'](arg1);
}

export function ListPackLibrary() {
  return window['go']['app']['App']['ListPackLibrary']();
}

export function ListResumableRuns() {
  return window['go']['app']['App']['ListResumableRuns']();
}

export function ListSessionSummaries() {
  return window['go']['app']['App']['ListSessionSummaries']();
}

export function ListSessions() {
  return window['go']['app']['App']['ListSessions']();
}

export function ListSkills() {
  return window['go']['app']['App']['ListSkills']();
}

export function ListStorageItems() {
  return window['go']['app']['App']['ListStorageItems']();
}

export function ListTaskRuns() {
  return window['go']['app']['App']['ListTaskRuns']();
}

export function ListTodos() {
  return window['go']['app']['App']['ListTodos']();
}

export function ListVPNInterfaces() {
  return window['go']['app']['App']['ListVPNInterfaces']();
}

export function ListWSLDistros() {
  return window['go']['app']['App']['ListWSLDistros']();
}

export function ListWorkspaceFolders() {
  return window['go']['app']['App']['ListWorkspaceFolders']();
}

export function LoadBenchmarkModel(arg1, arg2) {
  return window['go']['app']['App']['LoadBenchmarkModel'](arg1, arg2);
}

export function LoadSession(arg1) {
  return window['go']['app']['App']['LoadSession'](arg1);
}

export function OpenShell() {
  return window['go']['app']['App']['OpenShell']();
}

export function PauseBrowserWorkflow() {
  return window['go']['app']['App']['PauseBrowserWorkflow']();
}

export function PickSaveFilePath(arg1) {
  return window['go']['app']['App']['PickSaveFilePath'](arg1);
}

export function Ping() {
  return window['go']['app']['App']['Ping']();
}

export function PingProvider(arg1) {
  return window['go']['app']['App']['PingProvider'](arg1);
}

export function PrepareChatAttachmentPath(arg1) {
  return window['go']['app']['App']['PrepareChatAttachmentPath'](arg1);
}

export function PreviewContext(arg1, arg2) {
  return window['go']['app']['App']['PreviewContext'](arg1, arg2);
}

export function PreviewRepositorySplitReview(arg1) {
  return window['go']['app']['App']['PreviewRepositorySplitReview'](arg1);
}

export function PromoteScratchWorkspace(arg1) {
  return window['go']['app']['App']['PromoteScratchWorkspace'](arg1);
}

export function PruneLedgerEvents(arg1, arg2) {
  return window['go']['app']['App']['PruneLedgerEvents'](arg1, arg2);
}

export function ReadFileContent(arg1) {
  return window['go']['app']['App']['ReadFileContent'](arg1);
}

export function RecommendModelProfileTemplate(arg1) {
  return window['go']['app']['App']['RecommendModelProfileTemplate'](arg1);
}

export function RecordLearningDecision(arg1, arg2, arg3) {
  return window['go']['app']['App']['RecordLearningDecision'](arg1, arg2, arg3);
}

export function RecoverSharedTerminal() {
  return window['go']['app']['App']['RecoverSharedTerminal']();
}

export function RefreshWorkspaceRepositoryIndex() {
  return window['go']['app']['App']['RefreshWorkspaceRepositoryIndex']();
}

export function ReindexSessionRecall() {
  return window['go']['app']['App']['ReindexSessionRecall']();
}

export function ReleaseEngagementClaim(arg1, arg2) {
  return window['go']['app']['App']['ReleaseEngagementClaim'](arg1, arg2);
}

export function RemoveRepositoryIndexSource(arg1) {
  return window['go']['app']['App']['RemoveRepositoryIndexSource'](arg1);
}

export function RemoveWorkspaceFolder(arg1) {
  return window['go']['app']['App']['RemoveWorkspaceFolder'](arg1);
}

export function RenameFile(arg1, arg2) {
  return window['go']['app']['App']['RenameFile'](arg1, arg2);
}

export function RenameSession(arg1, arg2) {
  return window['go']['app']['App']['RenameSession'](arg1, arg2);
}

export function RepairSession(arg1) {
  return window['go']['app']['App']['RepairSession'](arg1);
}

export function RespondConfirm(arg1) {
  return window['go']['app']['App']['RespondConfirm'](arg1);
}

export function RestartAudioWorker() {
  return window['go']['app']['App']['RestartAudioWorker']();
}

export function RestartWSL() {
  return window['go']['app']['App']['RestartWSL']();
}

export function ResumeBrowserWorkflow() {
  return window['go']['app']['App']['ResumeBrowserWorkflow']();
}

export function ResumeBrowserWorkflowCheckpoint(arg1) {
  return window['go']['app']['App']['ResumeBrowserWorkflowCheckpoint'](arg1);
}

export function ResumeRepositorySplitReview() {
  return window['go']['app']['App']['ResumeRepositorySplitReview']();
}

export function ResumeRun(arg1) {
  return window['go']['app']['App']['ResumeRun'](arg1);
}

export function RetryRepositoryReviewShard(arg1) {
  return window['go']['app']['App']['RetryRepositoryReviewShard'](arg1);
}

export function RollbackDepth() {
  return window['go']['app']['App']['RollbackDepth']();
}

export function RunAgentEval(arg1) {
  return window['go']['app']['App']['RunAgentEval'](arg1);
}

export function RunAgentEvalRepeated(arg1, arg2) {
  return window['go']['app']['App']['RunAgentEvalRepeated'](arg1, arg2);
}

export function RunArtifact(arg1, arg2) {
  return window['go']['app']['App']['RunArtifact'](arg1, arg2);
}

export function RunContextQualityEval(arg1, arg2) {
  return window['go']['app']['App']['RunContextQualityEval'](arg1, arg2);
}

export function RunDoctor() {
  return window['go']['app']['App']['RunDoctor']();
}

export function RunEngagementAgentEval() {
  return window['go']['app']['App']['RunEngagementAgentEval']();
}

export function RunGrammarToolArgsProbe(arg1) {
  return window['go']['app']['App']['RunGrammarToolArgsProbe'](arg1);
}

export function RunJHUTAgentEval(arg1) {
  return window['go']['app']['App']['RunJHUTAgentEval'](arg1);
}

export function RunJHUTBrowserVerification(arg1) {
  return window['go']['app']['App']['RunJHUTBrowserVerification'](arg1);
}

export function RunMiniAgentLoopBenchmark(arg1, arg2) {
  return window['go']['app']['App']['RunMiniAgentLoopBenchmark'](arg1, arg2);
}

export function SaveBrowserWorkflowCheckpoint(arg1) {
  return window['go']['app']['App']['SaveBrowserWorkflowCheckpoint'](arg1);
}

export function SaveConversationCheckpoint(arg1, arg2) {
  return window['go']['app']['App']['SaveConversationCheckpoint'](arg1, arg2);
}

export function SaveFileContent(arg1, arg2) {
  return window['go']['app']['App']['SaveFileContent'](arg1, arg2);
}

export function SaveMemoryEntry(arg1) {
  return window['go']['app']['App']['SaveMemoryEntry'](arg1);
}

export function SaveSession(arg1) {
  return window['go']['app']['App']['SaveSession'](arg1);
}

export function SaveSkill(arg1) {
  return window['go']['app']['App']['SaveSkill'](arg1);
}

export function SaveUserProfile(arg1) {
  return window['go']['app']['App']['SaveUserProfile'](arg1);
}

export function ScaffoldWorkspaceFolders(arg1, arg2) {
  return window['go']['app']['App']['ScaffoldWorkspaceFolders'](arg1, arg2);
}

export function SearchSessionRecall(arg1, arg2) {
  return window['go']['app']['App']['SearchSessionRecall'](arg1, arg2);
}

export function SelectChatFiles() {
  return window['go']['app']['App']['SelectChatFiles']();
}

export function SelectProjectInstructionDirectory(arg1) {
  return window['go']['app']['App']['SelectProjectInstructionDirectory'](arg1);
}

export function SelectProjectInstructionFile(arg1) {
  return window['go']['app']['App']['SelectProjectInstructionFile'](arg1);
}

export function SelectRepositoryIndexFiles() {
  return window['go']['app']['App']['SelectRepositoryIndexFiles']();
}

export function SelectRepositoryIndexFolder() {
  return window['go']['app']['App']['SelectRepositoryIndexFolder']();
}

export function SelectWorkingDir(arg1) {
  return window['go']['app']['App']['SelectWorkingDir'](arg1);
}

export function SelectWorkspaceFolder(arg1) {
  return window['go']['app']['App']['SelectWorkspaceFolder'](arg1);
}

export function SendMessage(arg1, arg2, arg3) {
  return window['go']['app']['App']['SendMessage'](arg1, arg2, arg3);
}

export function SendMessageWithProfile(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SendMessageWithProfile'](arg1, arg2, arg3, arg4);
}

export function SendTelegramMessage(arg1, arg2) {
  return window['go']['app']['App']['SendTelegramMessage'](arg1, arg2);
}

export function SetAgentModeOverride(arg1) {
  return window['go']['app']['App']['SetAgentModeOverride'](arg1);
}

export function SetAutoAgents(arg1) {
  return window['go']['app']['App']['SetAutoAgents'](arg1);
}

export function SetAutonomous(arg1) {
  return window['go']['app']['App']['SetAutonomous'](arg1);
}

export function SetConversationMode(arg1, arg2) {
  return window['go']['app']['App']['SetConversationMode'](arg1, arg2);
}

export function SetEngagementEndpointGroup(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetEngagementEndpointGroup'](arg1, arg2, arg3);
}

export function SetEngagementNotes(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetEngagementNotes'](arg1, arg2, arg3);
}

export function SetNextContextPacketClass(arg1) {
  return window['go']['app']['App']['SetNextContextPacketClass'](arg1);
}

export function SetPackArchived(arg1, arg2) {
  return window['go']['app']['App']['SetPackArchived'](arg1, arg2);
}

export function SetProviderAPIKey(arg1, arg2) {
  return window['go']['app']['App']['SetProviderAPIKey'](arg1, arg2);
}

export function SetRepositoryIndexWatch(arg1) {
  return window['go']['app']['App']['SetRepositoryIndexWatch'](arg1);
}

export function SetSavedConversationMode(arg1, arg2) {
  return window['go']['app']['App']['SetSavedConversationMode'](arg1, arg2);
}

export function SetSessionTags(arg1, arg2) {
  return window['go']['app']['App']['SetSessionTags'](arg1, arg2);
}

export function SetSpecMode(arg1) {
  return window['go']['app']['App']['SetSpecMode'](arg1);
}

export function SetWorkingDir(arg1) {
  return window['go']['app']['App']['SetWorkingDir'](arg1);
}

export function ShellClose(arg1) {
  return window['go']['app']['App']['ShellClose'](arg1);
}

export function ShellInput(arg1, arg2) {
  return window['go']['app']['App']['ShellInput'](arg1, arg2);
}

export function ShellResize(arg1, arg2, arg3) {
  return window['go']['app']['App']['ShellResize'](arg1, arg2, arg3);
}

export function StartBrowserWorkflow(arg1) {
  return window['go']['app']['App']['StartBrowserWorkflow'](arg1);
}

export function StartRepositorySplitReview(arg1) {
  return window['go']['app']['App']['StartRepositorySplitReview'](arg1);
}

export function StopAgent() {
  return window['go']['app']['App']['StopAgent']();
}

export function StopArtifact() {
  return window['go']['app']['App']['StopArtifact']();
}

export function StopBrowserWorkflow() {
  return window['go']['app']['App']['StopBrowserWorkflow']();
}

export function SwitchProfile(arg1) {
  return window['go']['app']['App']['SwitchProfile'](arg1);
}

export function SynthesizeSpeech(arg1) {
  return window['go']['app']['App']['SynthesizeSpeech'](arg1);
}

export function TakeOverBrowserWorkflow() {
  return window['go']['app']['App']['TakeOverBrowserWorkflow']();
}

export function TranscribeVoiceClip(arg1) {
  return window['go']['app']['App']['TranscribeVoiceClip'](arg1);
}

export function Undo() {
  return window['go']['app']['App']['Undo']();
}

export function UpdateLabContext(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['UpdateLabContext'](arg1, arg2, arg3, arg4);
}

export function UpdateProfiles(arg1) {
  return window['go']['app']['App']['UpdateProfiles'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['app']['App']['UpdateSettings'](arg1);
}

export function UpsertEngagementFinding(arg1, arg2) {
  return window['go']['app']['App']['UpsertEngagementFinding'](arg1, arg2);
}

export function UseProfile(arg1, arg2, arg3) {
  return window['go']['app']['App']['UseProfile'](arg1, arg2, arg3);
}

export function UseProjectInstructionFile(arg1) {
  return window['go']['app']['App']['UseProjectInstructionFile'](arg1);
}
